usage: extract.py [-h] [--checkpoint_path CHECKPOINT_PATH]
                  [--output_dir OUTPUT_DIR] [--mask_data MASK_DATA]
                  [--cuda_device CUDA_DEVICE] [--max_len MAX_LEN]
                  [--batch_size BATCH_SIZE] [--epochs EPOCHS]
                  [--num_class NUM_CLASS] [--weight_vec WEIGHT_VEC]
extract.py: error: argument --weight_vec: invalid int value: '[0.1,.8,.8,.8,.8,.8,.8,.8,.8,.8,.8]'
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x2b7c6ef92e18>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
