/home/sanne/.local/lib/python3.5/site-packages/torch/serialization.py:325: SourceChangeWarning: source code of class 'torch.nn.modules.rnn.LSTM' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/sanne/.local/lib/python3.5/site-packages/torch/serialization.py:325: SourceChangeWarning: source code of class 'torch.nn.modules.sparse.Embedding' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/sanne/.local/lib/python3.5/site-packages/torch/serialization.py:325: SourceChangeWarning: source code of class 'torch.nn.modules.linear.Linear' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/sanne/.local/lib/python3.5/site-packages/torch/serialization.py:325: SourceChangeWarning: source code of class 'torch.nn.modules.rnn.LSTM' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/sanne/.local/lib/python3.5/site-packages/torch/serialization.py:325: SourceChangeWarning: source code of class 'torch.nn.modules.sparse.Embedding' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/sanne/.local/lib/python3.5/site-packages/torch/serialization.py:325: SourceChangeWarning: source code of class 'torch.nn.modules.linear.Linear' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
Exception ignored in: <bound method DropoutDescriptor.__del__ of <torch.backends.cudnn.DropoutDescriptor object at 0x2b4f4e7f2630>>
Traceback (most recent call last):
  File "/home/sanne/.local/lib/python3.5/site-packages/torch/backends/cudnn/__init__.py", line 238, in __del__
AttributeError: 'NoneType' object has no attribute 'cudnnDestroyDropoutDescriptor'
Exception ignored in: <bound method DropoutDescriptor.__del__ of <torch.backends.cudnn.DropoutDescriptor object at 0x2b4f4e7f26a0>>
Traceback (most recent call last):
  File "/home/sanne/.local/lib/python3.5/site-packages/torch/backends/cudnn/__init__.py", line 238, in __del__
AttributeError: 'NoneType' object has no attribute 'cudnnDestroyDropoutDescriptor'
Exception ignored in: <bound method CuDNNHandle.__del__ of <torch.backends.cudnn.CuDNNHandle object at 0x2b4f4e7f2b00>>
Traceback (most recent call last):
  File "/home/sanne/.local/lib/python3.5/site-packages/torch/backends/cudnn/__init__.py", line 114, in __del__
AttributeError: 'NoneType' object has no attribute 'cudnnDestroy'
/var/spool/torque/mom_priv/jobs/1574691.batch1.lisa.surfsara.nl.SC: line 25: echoAgain and again: command not found
Exception ignored in: <bound method DropoutDescriptor.__del__ of <torch.backends.cudnn.DropoutDescriptor object at 0x2b251f684240>>
Traceback (most recent call last):
  File "/home/sanne/.local/lib/python3.5/site-packages/torch/backends/cudnn/__init__.py", line 238, in __del__
AttributeError: 'NoneType' object has no attribute 'cudnnDestroyDropoutDescriptor'
Exception ignored in: <bound method DropoutDescriptor.__del__ of <torch.backends.cudnn.DropoutDescriptor object at 0x2b251f684ba8>>
Traceback (most recent call last):
  File "/home/sanne/.local/lib/python3.5/site-packages/torch/backends/cudnn/__init__.py", line 238, in __del__
AttributeError: 'NoneType' object has no attribute 'cudnnDestroyDropoutDescriptor'
Exception ignored in: <bound method CuDNNHandle.__del__ of <torch.backends.cudnn.CuDNNHandle object at 0x2b251f684b70>>
Traceback (most recent call last):
  File "/home/sanne/.local/lib/python3.5/site-packages/torch/backends/cudnn/__init__.py", line 114, in __del__
AttributeError: 'NoneType' object has no attribute 'cudnnDestroy'
Traceback (most recent call last):
  File "evaluate.py", line 74, in <module>
    checkpoint = Checkpoint.load(opt.checkpoint_path)
  File "/home/sanne/machine/sanne/machine/seq2seq/util/checkpoint.py", line 95, in load
    resume_checkpoint = torch.load(os.path.join(path, cls.TRAINER_STATE_NAME))
  File "/home/sanne/.local/lib/python3.5/site-packages/torch/serialization.py", line 265, in load
    f = open(f, 'rb')

FileNotFoundError: [Errno 2] No such file or directory: 'model-final-new-2/acc_1.00_seq_acc_1.00_ppl_1.00_s5670/trainer_states.pt'
Traceback (most recent call last):
  File "evaluate.py", line 74, in <module>
    checkpoint = Checkpoint.load(opt.checkpoint_path)
  File "/home/sanne/machine/sanne/machine/seq2seq/util/checkpoint.py", line 95, in load
    resume_checkpoint = torch.load(os.path.join(path, cls.TRAINER_STATE_NAME))
  File "/home/sanne/.local/lib/python3.5/site-packages/torch/serialization.py", line 265, in load
    f = open(f, 'rb')

FileNotFoundError: [Errno 2] No such file or directory: 'model-final-new-3/acc_1.00_seq_acc_1.00_ppl_1.00_s5670/trainer_states.pt'
Traceback (most recent call last):
  File "evaluate.py", line 74, in <module>
    checkpoint = Checkpoint.load(opt.checkpoint_path)
  File "/home/sanne/machine/sanne/machine/seq2seq/util/checkpoint.py", line 95, in load
    resume_checkpoint = torch.load(os.path.join(path, cls.TRAINER_STATE_NAME))
  File "/home/sanne/.local/lib/python3.5/site-packages/torch/serialization.py", line 265, in load
    f = open(f, 'rb')

FileNotFoundError: [Errno 2] No such file or directory: 'model-final-new-1/acc_1.00_seq_acc_1.00_ppl_1.00_s5670/trainer_states.pt'
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x2ab5ab407e18>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
